name: albunaut
description: Display ListenBrainz stats
publish_to: none
version: 0.1.1+2

environment:
  flutter: ^3.38.5
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  collection: any
  drift: 2.30.0
  file_picker: 10.3.8
  intl: any
  path: 1.9.1
  path_provider: 2.1.5
  shared_preferences: 2.5.4
  sqlite3: 2.9.4
  sqlite3_flutter_libs: 0.5.41
  url_launcher: 6.3.2

  help_page:
    git:
      url: https://github.com/z80maniac/flutter_help_page.git
      ref: c6e76a5b30a33cce197f80643fbb5f44551ee86a
  mega_form:
    git:
      url: https://github.com/z80maniac/mega_form.git
      ref: e93145d5010476a296df7623676da5631a24673f
  pad5:
    git:
      url: https://github.com/z80maniac/pad5.git
      ref: 33f4004b677409f56a77415ce55d14a4157c28e0
  typed_prefs:
    git:
      url: https://github.com/z80maniac/typed_prefs.git
      ref: 031b1bd7aa133ba9c40b5a1804ba32c8e37a13ba

dev_dependencies:
  build_runner: 2.10.4
  drift_dev: 2.30.0
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
